# Generated by Django 5.1.5 on 2025-04-02 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFinancial',
            fields=[
                ('financial_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_id', models.IntegerField()),
                ('activity_date', models.DateField()),
                ('gift_card_purchased', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('gift_card_redeemed', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('skip_the_dishes', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('just_eat', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('amex', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('din_club', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('discover', models.DecimalField(decimal_places=2, max_digits=30)),
                ('master_card', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('visa', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('dr_card', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('financial_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('actual_deposit_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('required_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activity_financial',
            },
        ),
        migrations.CreateModel(
            name='ActivityPaidOut',
            fields=[
                ('paid_out_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_date', models.DateField()),
                ('site_id', models.IntegerField()),
                ('food_paid_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('liquor_paid_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('supplies_paid_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('repair_maintenance', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('advertising', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('entertainment', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('others', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('hst_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('paid_out_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activity_paid_out',
            },
        ),
        migrations.CreateModel(
            name='ActivityPromotions',
            fields=[
                ('promotions_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_date', models.DateField()),
                ('site_id', models.IntegerField()),
                ('staff_meals', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('manager_meals', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('coupons_disc', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('chucks_bucks', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('manager_prom', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('qsa_complaints', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('lsm_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('lsm_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('promotion_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activity_promotions',
            },
        ),
        migrations.CreateModel(
            name='ActivityPurchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_id', models.IntegerField()),
                ('activity_date', models.DateField()),
                ('purchases_food', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('purchases_paper', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('purchases_liquor', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activity_purchase',
            },
        ),
        migrations.CreateModel(
            name='ActivitySales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_id', models.IntegerField()),
                ('activity_date', models.DateField()),
                ('food', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('liquor', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('beer', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('wine', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('beverages_iced_beverages', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('draft', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('honest_to_goodness_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('miscellaneous_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('sales_total', models.DecimalField(decimal_places=2, max_digits=40)),
                ('sales_tax1', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('sales_tax2', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('liquor_tax_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('customer_count', models.IntegerField()),
                ('sales_notes', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activity_sales',
            },
        ),
        migrations.CreateModel(
            name='compensation',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_id', models.IntegerField()),
                ('e_id', models.IntegerField()),
                ('employee_compensation_name', models.CharField(default='Unknown', max_length=255)),
                ('e_position', models.CharField(max_length=255)),
                ('e_position_type', models.CharField(max_length=255)),
                ('e_rate_type', models.CharField(max_length=50)),
                ('e_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('e_compensation_ffective_Date', models.DateField()),
                ('e_comp_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_inactive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'compensation',
            },
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_id', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('phone1', models.CharField(blank=True, max_length=15, null=True)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('smart_serve', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_inactive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'employee',
                'unique_together': {('employee_name', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('timesheet_id', models.AutoField(primary_key=True, serialize=False)),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('submission_datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_panel.employee')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayDailyEntry',
            fields=[
                ('pay_daily_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_date', models.DateField()),
                ('regular_hrs_worked', models.IntegerField(default=0)),
                ('overtime_hr', models.IntegerField(default=0)),
                ('daily_hourly_rate', models.IntegerField()),
                ('total_daily_rate', models.IntegerField()),
                ('leave', models.IntegerField(default=0)),
                ('holiday', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_panel.compensation')),
                ('timesheet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_panel.timesheet')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('browser_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
